### ISSUE TITLE
But where are the sources?

### ISSUE THREAD

**Issue by dmythro** [touchduck/dynamon#2]
Sceenshots look good, but where are the sources?

**Comment by Vadorequest** [comment]
And how to install?

I'm also concerned by the source, since it's asking for AWS permissions, which I'm not willing to give if I don't know what's done with them.

**Comment by MikeCodesDotNET** [comment]
Why are you hosting on Github if you're not sharing the source?

**Comment by touchduck** [comment]
i am too busy. i thinking add feature, but slow.. slow..
