### ISSUE TITLE
Crash with some tables after 'Start search' pushed

### ISSUE THREAD

**Issue by dimgord** [touchduck/dynamon#7]
Hi touchduck,

First of all, thank you very much for the app,  I really like it, it is the only app I could find which supports GSI.

Could you please take a look at the crash stack and try to at least point me to some workaround?  I gave Full Disk Access to the Dynamon, as well as added it to Accessibility and Input Monitoring (maybe I should do something else?) but still has this annoying crash :/ . I couldn't find anything specific in the crashing tables, they are pretty small (150 records, test db).

Please help me!

Thank you,
dimgord

P.S. Please leet me know if you need full CrashReport

============================

Process:               Dynamon [19545]
Path:                  /Applications/Dynamon.app/Contents/MacOS/Dynamon
Identifier:            com.cdonut.dynamon
Version:               1.0.5 (1)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Dynamon [19545]
User ID:               360341854

Date/Time:             2020-01-20 13:15:45.305 -0500
OS Version:            Mac OS X 10.15.2 (19C57)
Report Version:        12
Bridge OS Version:     3.0 (14Y908)
Anonymous UUID:        7A31692F-2307-0D28-D685-1FADD558A5D4

Sleep/Wake UUID:       5F83798D-C1FD-4B1E-B25F-82E71E08EAE0

Time Awake Since Boot: 25000 seconds
Time Since Wake:       17000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000233b1a7130f8
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [19545]

VM Regions Near 0x233b1a7130f8:
    mapped file            000000010cdf7000-000000010e8a4000 [ 26.7M] r--/r-- SM=ALI  
--> 
    MALLOC_NANO            0000600000000000-0000600008000000 [128.0M] rw-/rwx SM=PRV  

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   com.cdonut.dynamon            	0x0000000104e75158 0x104a78000 + 4182360
1   com.cdonut.dynamon            	0x0000000104e751c6 0x104a78000 + 4182470
2   com.cdonut.dynamon            	0x0000000104e74bbd 0x104a78000 + 4180925
3   com.cdonut.dynamon            	0x0000000104eb63a1 0x104a78000 + 4449185
4   com.cdonut.dynamon            	0x0000000104a854d0 0x104a78000 + 54480
5   com.cdonut.dynamon            	0x0000000104a9586f 0x104a78000 + 120943
6   com.cdonut.dynamon            	0x0000000104a9599d 0x104a78000 + 121245
7   com.apple.AppKit              	0x00007fff2d4991c6 -[NSTableView(NSTableViewViewBased) _delegate_viewForTableColumn:row:] + 88
8   com.apple.AppKit              	0x00007fff2d3a9f9e -[NSTableView(NSTableViewViewBased) makeViewForTableColumn:row:] + 87
9   com.apple.AppKit              	0x00007fff2d3a951d -[NSTableRowData _addViewToRowView:atColumn:row:] + 327
10  com.apple.AppKit              	0x00007fff2d3a9257 -[NSTableRowData _addViewsToRowView:atRow:] + 191
11  com.apple.AppKit              	0x00007fff2d3a7296 -[NSTableRowData _initializeRowView:atRow:] + 391
12  com.apple.AppKit              	0x00007fff2d3a55a6 -[NSTableRowData _preparedRowViewForRow:storageHandler:] + 140
13  com.apple.AppKit              	0x00007fff2d3a53ab -[NSTableRowData _addRowViewForVisibleRow:withPriorView:] + 276
14  com.apple.AppKit              	0x00007fff2d3a51f9 -[NSTableRowData _addRowViewForVisibleRow:withPriorRowIndex:inDictionary:withRowAnimation:] + 361
15  com.apple.AppKit              	0x00007fff2d3a3f36 -[NSTableRowData _updateVisibleRowEntries] + 816
16  com.apple.AppKit              	0x00007fff2d3a39d3 -[NSTableRowData updateVisibleRowViews] + 372
17  com.apple.AppKit              	0x00007fff2d3a3101 -[NSTableView layout] + 184
18  com.apple.AppKit              	0x00007fff2d346410 _NSViewLayout + 600
19  com.apple.AppKit              	0x00007fff2d345eb3 -[NSView _layoutSubtreeWithOldSize:] + 388
20  com.apple.AppKit              	0x00007fff2d34600d -[NSView _layoutSubtreeWithOldSize:] + 734
21  com.apple.AppKit              	0x00007fff2d34600d -[NSView _layoutSubtreeWithOldSize:] + 734
22  com.apple.AppKit              	0x00007fff2d34600d -[NSView _layoutSubtreeWithOldSize:] + 734
23  com.apple.AppKit              	0x00007fff2d34600d -[NSView _layoutSubtreeWithOldSize:] + 734
24  com.apple.AppKit              	0x00007fff2d34600d -[NSView _layoutSubtreeWithOldSize:] + 734
25  com.apple.AppKit              	0x00007fff2d34600d -[NSView _layoutSubtreeWithOldSize:] + 734
26  com.apple.AppKit              	0x00007fff2d34600d -[NSView _layoutSubtreeWithOldSize:] + 734
27  com.apple.AppKit              	0x00007fff2d34600d -[NSView _layoutSubtreeWithOldSize:] + 734
28  com.apple.AppKit              	0x00007fff2d34600d -[NSView _layoutSubtreeWithOldSize:] + 734
29  com.apple.AppKit              	0x00007fff2d34600d -[NSView _layoutSubtreeWithOldSize:] + 734
30  com.apple.AppKit              	0x00007fff2d3452e2 -[NSView _layoutSubtreeIfNeededAndAllowTemporaryEngine:] + 1137
31  com.apple.AppKit              	0x00007fff2d344d7e -[NSWindow(NSConstraintBasedLayout) _layoutViewTree] + 148
32  com.apple.AppKit              	0x00007fff2d3cb69e -[NSWindow(NSConstraintBasedLayout) layoutIfNeeded] + 251
33  com.apple.AppKit              	0x00007fff2d3cb4dc __NSWindowGetDisplayCycleObserverForLayout_block_invoke + 430
34  com.apple.AppKit              	0x00007fff2d3ca621 NSDisplayCycleObserverInvoke + 155
35  com.apple.AppKit              	0x00007fff2d3ca1e8 NSDisplayCycleFlush + 977
36  com.apple.QuartzCore          	0x00007fff3b926112 CA::Transaction::run_commit_handlers(CATransactionPhase) + 100
37  com.apple.QuartzCore          	0x00007fff3b924e64 CA::Transaction::commit() + 224
38  com.apple.AppKit              	0x00007fff2d486e87 __62+[CATransaction(NSCATransaction) NS_setFlushesWithDisplayLink]_block_invoke + 266
39  com.apple.AppKit              	0x00007fff2dba277d ___NSRunLoopObserverCreateWithHandler_block_invoke + 41
40  com.apple.CoreFoundation      	0x00007fff3011f0ee __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
41  com.apple.CoreFoundation      	0x00007fff3011f014 __CFRunLoopDoObservers + 457
42  com.apple.CoreFoundation      	0x00007fff3011e70b __CFRunLoopRun + 1219
43  com.apple.CoreFoundation      	0x00007fff3011dbd3 CFRunLoopRunSpecific + 499
44  com.apple.HIToolbox           	0x00007fff2ec7465d RunCurrentEventLoopInMode + 292
45  com.apple.HIToolbox           	0x00007fff2ec7439d ReceiveNextEventCommon + 600
46  com.apple.HIToolbox           	0x00007fff2ec74127 _BlockUntilNextEventMatchingListInModeWithFilter + 64
47  com.apple.AppKit              	0x00007fff2d2e5eb4 _DPSNextEvent + 990
48  com.apple.AppKit              	0x00007fff2d2e4690 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1352
49  com.apple.AppKit              	0x00007fff2d2d63ae -[NSApplication run] + 658
50  com.apple.AppKit              	0x00007fff2d2a8775 NSApplicationMain + 777
51  com.cdonut.dynamon            	0x0000000104a8bd39 0x104a78000 + 81209
52  libdyld.dylib                 	0x00007fff6777a7fd start + 1

**Comment by touchduck** [comment]
Hi dimgord,

i tried 150 record.
but not riased error
so, i do version up library.
you can download new app.

Thank you

**Comment by dimgord** [comment]
Awesome, thank you very much, it works great!
